source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PLStreamingKit_Example', :exclusive => true do
  pod "PLStreamingKit", :path => "../"
  pod "GPUImage"
end

target 'PLStreamingKit_Tests', :exclusive => true do
  pod "PLStreamingKit", :path => "../"


end
